base_url: http://juliananazare.com

github_link: http://github.com/jnazare 
linkedin_link: http://linkedin.com/in/juliananazare 
twitter_link: http://twitter.com/@juliananazare
instagram_link: http://instagram.com/jules065
email_link: mailto:juliana@media.mit.edu